#pragma once
#include <3ds/types.h>

#define PDN_INVALID_ARG    MAKERESULT(RL_USAGE, RS_INVALIDARG, RM_PDN, 1)

#define PDN_INTERNAL_RANGE MAKERESULT(RL_FATAL, RS_INTERNAL, RM_PDN, RD_OUT_OF_RANGE)
#define PDN_CANCELED_RANGE MAKERESULT(RL_FATAL, RS_CANCELED, RM_PDN, RD_OUT_OF_RANGE)
